name: dart-cpu-temp
on: [push]
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: dart-cpu-temp
