name: dart-cpu-temp
on: [push]
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name:
        run: docker build -t dart ./
      - name:
        run: docker stop dart || true
      - name:
        run: docker run -d -p 50051:50051 dart
